STAR_FACTS = [
    "At the most conservative estimate, there are at least 10 billion trillion stars in the universe.",
    "Red stars are relatively small and cool, while the hottest burn blue-white.",
    "Medieval alchemists studied the North Star, believing it held the secret to perpetual motion.",
    "Stars are formed from dense knots contained in large clouds of dust and gas called nebulae.",
    "There is enough matter in the Orion Nebula to produce over 10,000 stars.",
    "The ancient Greeks believed that the stars and all other heavenly bodies made a daily rotation around the Earth.",
    "By astronomical standards, a star that was formed 2 million years ago is considered to still be in its youth.",
    "Supergiants are massive stars that are hundreds of times the size of our sun.",
    "Our sun was formed 4600 million years ago and is expected to live a total of 10,000 million years.",
    "The nuclear reaction that takes place in a hydrogen bomb is the same reaction that fuels stars.",
    "The sun constitutes 99% of the total mass of our solar system.",
    "Every day, approximately 275 million new stars are formed in the universe.",
    "Given its chemical makeup, astronomers hypothesize that if you could taste the dust from the nebula that gave birth to our sun, it would taste like raspberries.",
    "A nebula that has only 6% less the mass of our sun cannot become a star; it will instead become a planet.",
    "Stars are deeply romantic for human beings and serve as a perennial symbol of progress and self-transcendence, as in the advice to 'reach for the stars.'",
    "When you look up at the night sky with the naked eye, every star you see is part of our own Milky Way Galaxy.",
    "The Milky Way Galaxy and the stars that it contains are, on average, around 13.6 billion years old.",
    "Most of the stars in the Milky Way lie in approximately the same plane, meaning that our galaxy is basically a flat disc, 100,000 light years across.",
    "All stars are made of the same basic ingredients: hydrogen and helium.",
    "The Milky Way is set on a massive collision course with the neighboring Andromeda galaxy; the two galaxies will collide to form a mega-galaxy in about 4 billion years.",
    "The gas cloud surrounding the stars in the constellation Aquila contains enough alcohol to make 400 trillion pints of beer.",
    "Some of the oldest stars in the universe have gradually drifted to gather around our Milky Way Galaxy.",
    "Stars don't contain solid mass, but instead are combinations of gas and plasma.",
    "Three out of every five solar systems in the universe have two stars at their center instead of one.",
    "A star is considered to be dying once its energy production starts slowing, although it usually takes around 4 billion years for a star to be entirely cooled down.",
    "The earliest known person to suggest that the Earth was actually a planet rotating around a star was Aristarchus of Samos. His ancient Greek contemporaries ridiculed his “outlandish” ideas.",
    "It takes so long for a star to die that astronomers have not yet observed a fully dead star.",
    "Any quantity of billions upon billions of things, such as the number of stars in the universe, is known as a “sagan,” after the cosmologist Carl Sagan.",
    "At 350,000 stars, astronomer Annie Jump Cannon holds the record for most stars classified in a lifetime.",
    "The first recorded supernova—a star that has collapsed in on itself—was observed in China in 185 AD. Nearly 2000 years later, astronomers at the University of Utrect identified the burnt-out remains of that same star.",
    "When British astronomers Antony Hewish, Jocelyn Bell Burnell, and Martin Ryle discovered pulsars—swiftly blinking celestial bodies—they jokingly named them LGMs, for 'little green men.'",
    "The earliest known female astronomer was Hypatia of Alexandria (355-415 AD). Hypatia taught many students and was a widely recognized authority on philosophy, astronomy, and mathematics.",
    "Some of the first people to accept Copernicus' assertion that the Earth was revolving around the sun were astrologers, who believed that his astronomical model would allow them to make 'more reliable horoscopes.'",
    "The word 'planet' comes from a Greek word meaning 'wandering star.'",
    "Nicolaus Copernicus developed his theory of a heliocentric solar system while working to create a better calendar for the Catholic Church in 1514.",
    "In recent years, several companies have begun “selling” star names to unwitting customers who don't realize that these companies—and therefore the names the customer pays for—are not recognized by any official astronomical organization.",
    "Stars that have the least amount of mass have the longest lifetimes, surviving for as many as a million million years.",
    "Astronaut Virgil Grissom secretly changed the names of some of the stars in NASA's star charts in the late 1960s to 'Navi,' 'Regor,' and 'Dnoces,' (Ivan, Roger, and Second backwards) as an inside joke with his fellow astronauts. It wasn't until the 1970s that NASA caught the practical joke and fixed the charts.",
    "The Caldwell Catalogue is a complete list of the 109 astronomical objects that are observable by an amateur astronomer.",
    "In 2011, the Kepler Space Telescope team discovered a star that was emitting strange light patterns. After astronomers across the world failed to find natural explanations for this phenomenon, many scientists and laypeople alike have begun to speculate that the star is being orbited by technological megastructures built by an alien civilization.",
    "Pulsars appear to be blinking stars, but they are actually city-sized, very dense bodies that pulse continuously. They are believed to be rotating neutron stars.",
    "Neutron stars contain roughly the same amount of mass as our sun, but all of that mass is condensed into an area the size of a small city.",
    "Because the sun is fairly average among stars, in both size and temperature, the famous cosmologist Carl Sagan called it a 'mediocre star.'",
    "A black hole, once a supermassive star, named Sagittarius A* sits at the center of the Milky Way Galaxy. It has a mass of approximately 4.3 million suns.",
]
